### ISSUE TITLE
CSV output broken

### ISSUE THREAD

**Issue by mmoya** [beancount/beanquery#167]
CSV output is broken in 2bf6dfb. Text output works OK.

```
  ...
  File "/home/mmoya/.cache/pypoetry/virtualenvs/mmoya-ledger-YHEMojRP-py3.11/lib/python3.11/site-packages/beanquery/query_render.py", line 548, in <listcomp>
    renderers = [_get_renderer(column.datatype, ctx) for column in columns]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mmoya/.cache/pypoetry/virtualenvs/mmoya-ledger-YHEMojRP-py3.11/lib/python3.11/site-packages/beanquery/query_render.py", line 467, in _get_renderer
    return renderer(ctx)
           ^^^^^^^^^^^^^
  File "/home/mmoya/.cache/pypoetry/virtualenvs/mmoya-ledger-YHEMojRP-py3.11/lib/python3.11/site-packages/beanquery/query_render.py", line 307, in __init__
    self.units_renderer = AmountRenderer(ctx)
                          ^^^^^^^^^^^^^^^^^^^
  File "/home/mmoya/.cache/pypoetry/virtualenvs/mmoya-ledger-YHEMojRP-py3.11/lib/python3.11/site-packages/beanquery/query_render.py", line 235, in __init__
    self.quantize = ctx.dcontext.quantize
                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_io.TextIOWrapper' object has no attribute 'quantize'
```

Last working commit was 804087a.

**Comment by mmoya** [comment]
This fixes the problem:

```patch
diff --git a/beanquery/render/csv.py b/beanquery/render/csv.py
index 01bd097..c979a83 100644
--- a/beanquery/render/csv.py
+++ b/beanquery/render/csv.py
@@ -2,4 +2,4 @@ from ..query_render import render_csv
 
 
 def render(desc, rows, file, *, dcontext, **kwargs):
-    return render_csv(desc, rows, file, dcontext, **kwargs)
+    return render_csv(desc, rows, dcontext, file, **kwargs)
